apiVersion: v1
kind: Pod
metadata:
  name: net-debug
spec:
  containers:
    - name: toolbox
      image: nicolaka/netshoot
      command: [ "sleep", "3600" ]  # 保证容器不退出
      stdin: true
      tty: true
  restartPolicy: Never