apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: jiangfz/online-chatroom-apiserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DYNAMODB_REGION
              value: "us-east-2"
            - name: WS_HOST
              value: "ws://ws-service:8081"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretKey
            - name: DYNAMODB_ENDPOINT
              value: ""
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
